<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Creates the `agent_domain_episodes` table.
 *
 * --- Explicit separation from `agent_episodes` ---
 *
 * agent_episodes        -> asynchronous compression pipeline (Python service)
 *                         write: EpisodicMemory::persist()
 *
 * agent_domain_episodes -> CortexOS's immutable domain episodes
 *                         write: EpisodeRepository::store()
 *                         read: ReflectTier2Job, Learner, observability
 *
 * --- String PK (ULID) ---
 *
 * episode_id is a ULID generated by the domain (Episode::generateId()),
 * prefixed with "ep_". ULIDs are sortable by timestamp, enabling
 * efficient historical queries without a separate index on created_at.
 *
 * --- JSON fields ---
 *
 * aligned_goals     -> list<string> of aligned strategic goal IDs.
 * alignment_traces  -> list<ExpansionTrace::toArray()>.
 * metrics           -> ExecutionMetrics::toArray() (iterations, tool_calls, latency).
 *
 * tool_trace is not persisted here, it lives in agent_episode_tool_traces
 * (EpisodeToolTraceRepository), due to volume and to make tool usage
 * pattern queries possible independent of the episode.
 *
 * --- Indexes ---
 *
 * idx_domain_eps_tenant_created   -> Learner: recentForTenant
 * idx_domain_eps_tenant_revision  -> ReflectTier2: forRevision (cross-analysis)
 * idx_domain_eps_tenant_session   -> debug / per-session observability
 *
 * @package Database\Migrations\V2\Agent
 * @author  Eduardo Costa Nkuansambu
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('agent_domain_episodes', function (Blueprint $table): void {

            // PK is the ULID generated by the domain, "ep_01JXYZ..."
            $table->string('episode_id', 32)->primary();

            $table->unsignedBigInteger('tenant_id')->index();
            $table->string('session_id');
            $table->text('input')->nullable();

            // Strategic alignment
            $table->json('aligned_goals');
            $table->json('alignment_traces')->nullable();

            // Execution metrics (ExecutionMetrics::toArray())
            $table->json('metrics');

            // Strategic goals revision active at the time of execution
            $table->string('strategic_revision');

            // EpisodeOutcome::value, completed | failed | partial | handoff | timeout
            $table->string('outcome', 32);

            // Compaction timestamp set by EpisodeCompactionJob (P5.3).
            // NULL until compacted. After compaction, input and
            // alignment_traces are nulled out, the identity fields never are.
            $table->timestamp('compacted_at')->nullable();

            // Immutable after creation, no updated_at
            $table->timestamp('created_at');

            $table->index(['tenant_id', 'created_at'], 'idx_domain_eps_tenant_created');
            $table->index(['tenant_id', 'strategic_revision'], 'idx_domain_eps_tenant_revision');
            $table->index(['tenant_id', 'session_id'], 'idx_domain_eps_tenant_session');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('agent_domain_episodes');
    }
};
