<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Creates the `agent_episodes` table.
 *
 * Raw episodic memory with an asynchronous compression pipeline via the
 * Python service. Distinct from `agent_domain_episodes` (CortexOS's
 * immutable domain episodes).
 *
 * --- Fields ---
 *
 * raw_data   -> raw data before compression; deleted after CompressEpisodeJob.
 * summary    -> compressed summary after asynchronous processing.
 * embedding  -> embedding generated by the Python service (JSON array of floats).
 * tool_trace -> sequence of tool calls in the episode (JSON); used by the
 *              PatternDetector for cross-episode pattern analysis. Nullable,
 *              episodes predating this field's introduction have no
 *              tool_trace; EpisodeRepository::hydrate() treats null as '[]'.
 *
 * @package Database\Migrations\V2\Agent
 * @author  Eduardo Costa Nkuansambu
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('agent_episodes', function (Blueprint $table): void {
            $table->id();
            $table->unsignedBigInteger('tenant_id')->index();
            $table->string('session_id')->index();
            $table->string('status', 32)->default('pending_compression')->index();

            // Raw data before compression (deleted after CompressEpisodeJob)
            $table->longText('raw_data')->nullable();

            // Compressed summary after asynchronous processing
            $table->text('summary')->nullable();

            // Embedding generated by the Python service (JSON array of floats)
            $table->longText('embedding')->nullable();

            // Strategic alignment (JSON array of ExpansionTrace)
            $table->json('alignment_traces')->nullable();

            // Sequence of tool calls, used by the PatternDetector.
            // Nullable: episodes without tool_trace are treated as '[]' in the repository.
            $table->json('tool_trace')->nullable();

            $table->string('version', 8)->default('v2')->index();
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('agent_episodes');
    }
};
